apiVersion: v1
kind: Pod
metadata:
  name: pod-volume
spec:
  containers:
  - name: nginx
    image: nginx:stable
    volumeMounts:
      - mountPath: /primeiro-volume
        name: primeiro-volume
  - name: jenkins
    image: jenkins:alpine
    volumeMounts:
      - mountPath: /primeiro-volume
        name: primeiro-volume
  volumes:
  - name: primeiro-volume
    hostPath:
      path: /home/gsadmin/Desktop/kubernets-study/
      type: DirectoryOrCreate

  