apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-portal-noticias-deployment
spec:
  template:
    metadata:
      name: db-portal-noticias-deployment
      labels:
        app: db-portal-noticias-deployment
    spec:
      containers:
        - name: db-portal-noticias-deployment
          image: aluracursos/mysql-db:1
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: db-portal-configmap
  selector:
    matchLabels:
      app: db-portal-noticias-deployment