apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: portal-noticias-replicaset
spec:
  template:
    metadata:
      name: portal-noticias-replicaset
      labels:
        app: portal-noticias-replicaset
    spec:
      containers:
        - name: portal-noticias-container
          image: aluracursos/portal-noticias:1
          ports:
            - containerPort: 80
  replicas: 3
  selector:
    matchLabels:
      app: portal-noticias-replicaset

